version: '3'

services:
  #
  # Applications
  bubble-proxy:
    image: ${COMPOSE_PROJECT_NAME}_entrypoint:latest
    container_name: ${COMPOSE_PROJECT_NAME}_entrypoint
    restart: unless-stopped
    expose:
      - "80"
    build:
      context: ./proxy
    environment:
      - DHPARAM_GENERATION=false
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - elabs-revproxy
      
networks:
  elabs-revproxy:
    external:
      name: ${APPS_NETWORK}